web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Activación del controlador de verificación de correo
Auth::routes(['verify' => true]);

//Ruta de Página principal
Route::resource('/', 'HomeController')->middleware(['checkUserStatus']);

//Ruta de perfil de usuario
Route::resource('miPerfil', 'PerfilController');
//Rutas para el crud de anuncios
Route::get('Perfil/Compraventa/show/{id}', 'AnunciosController@show')->name('Perfil.show');
Route::get('Perfil/Compraventa/detalles/{id}', 'AnunciosController@edit')->name('Perfil.detalles')->middleware(['auth']);
Route::post ('Perfil/update/{id}', 'AnunciosController@update')->name('Perfil.update')->middleware(['auth']);
Route::get('dts/{id}', 'AnunciosController@destroy')->name('dts');
//Rutas para el crud de tutorias
Route::get('Perfil/show2/{id}', 'TutoriasController@show')->name('Perfil.show2');
Route::get('Perfil/detalles2/{id}', 'TutoriasController@edit')->name('Perfil.detalles2')->middleware(['auth']);
Route::put ('Perfil/update2/{id}', 'TutoriasController@update')->name('Perfil.update2')->middleware(['auth']);
Route::get('dt/{id}', 'TutoriasController@destroy')->name('dt');
//Rutas para el crud de Bolsa de trabajo
Route::get('dB/{id}', 'BolsatrabajoController@destroy')->name('dtB');
//Rutas para el crud de Eventos
Route::get('Perfil/showE/{id}', 'EventoController@show')->name('Perfil.showE');
Route::get('Perfil/detallesE/{id}', 'EventoController@edit')->name('Perfil.detallesE')->middleware(['auth']);
Route::get('dE/{id}', 'EventoController@destroy')->name('dtE');
//Rutas para el crud de Alquiler y Hospedaje
Route::get('Perfil/showH/{id}', 'HospedajeController@show')->name('Perfil.showH');
Route::get('Perfil/detallesH/{id}', 'HospedajeController@edit')->name('Perfil.detallesH')->middleware(['auth']);
Route::put ('Perfil/updateH/{id}', 'HospedajeController@update')->name('Perfil.updateH')->middleware(['auth']);
Route::get('dtH/{id}', 'HospedajeController@destroy')->name('dtH');


//ruta para cargar carreras al formulario de editar el perfil
Route::get('miPerfil/getcarreras/{id}','PerfilController@getCarreras');
//Ruta de Actualización de Perfil
Route::post('miPerfil/updateProfile', 'PerfilController@updateProfile')->name('perfil.update')->middleware(['auth']);
//Ruta para mostrar los perfiles de los usuarios
Route::get('usuario/{email}', 'PerfilController@verPerfil')->name('perfil.verPerfil')->middleware(['auth','checkUserStatus']);
//Ruta de registro
Route::get('/register','RegistroController@getFacultades')->name('register');
Route::get('register/getcarreras/{id}','RegistroController@getCarreras');



//Rutas de Clasificados
Route::group(['prefix' => 'clasificado'], function () {
//Rutas de Compras/Ventas
Route::resource('anuncios','AnunciosController');
Route::get('/anuncios','AnunciosController@search')->name('anuncios.search');
Route::post('anuncios/update/{id}', 'AnunciosController@update')->name('anuncios.update')->middleware(['auth']);

//Ruta de tutorias
Route::resource('tutorias', 'TutoriasController');
Route::get('/tutorias','TutoriasController@search')->name('tutorias.search');
Route::post('tutorias/update/{id}', 'TutoriasController@update')->name('tutorias.update')->middleware(['auth']);

//Ruta de alquilerhospedaje
Route::resource('alquilerhospedajes', 'HospedajeController');
Route::get('/alquilerhospedajes','HospedajeController@search')->name('alquilerhospedajes.search');
Route::post('alquilerhospedajes/update/{id}', 'HospedajeController@update')->name('alquilerhospedajes.update')->middleware(['auth']);

});
//Ruta de bolsatrabajo
Route::resource('bolsatrabajos', 'BolsatrabajoController');
Route::get('bolsatrabajos','BolsatrabajoController@search')->name('bolsaDeTrabajo.search');
Route::post('bolsatrabajos/update/{id}', 'BolsatrabajoController@update')->name('bolsaDetrabajo.update')->middleware(['auth']);

//Ruta de Eventos
Route::resource('eventos','EventoController');
Route::get('/eventos','EventoController@searchE');
Route::post('eventos/update/{id}', 'EventoController@update')->name('eventos.update')->middleware(['auth']);

//Route::resource('eventos','EventoController@carga')->name('eventos');


## Rutas del panel de administración ##
    //Rutas de Gestión de Usuarios
    Route::get('usersAdmin/getUser/', 'AdminPanel\UsersAdminController@getUser')->name('usersAdmin.getUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/changeRole/{email}', 'AdminPanel\UsersAdminController@changeRole')->name('usersAdmin.changeRole')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/banUser/{email}', 'AdminPanel\UsersAdminController@banUser')->name('usersAdmin.banUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/reactivateUser/{email}', 'AdminPanel\UsersAdminController@reactivateUser')->name('usersAdmin.reactivateUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::resource('usersAdmin', 'AdminPanel\UsersAdminController')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Gestión de Facultades y Carreras
    Route::resource('degreesAdmin', 'AdminPanel\DegreesAdminController')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newFacultad', 'AdminPanel\DegreesAdminController@newFacultad')->name('degreeAdmin.newFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editFacultad/{id}', 'AdminPanel\DegreesAdminController@editFacultad')->name('degreeAdmin.editFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteFacultad/{id}', 'AdminPanel\DegreesAdminController@deleteFacultad')->name('degreeAdmin.deleteFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newCarrera/{id}', 'AdminPanel\DegreesAdminController@newCarrera')->name('degreeAdmin.newCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editCarrera/{id}', 'AdminPanel\DegreesAdminController@editCarrera')->name('degreeAdmin.editCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteCarrera/{id}', 'AdminPanel\DegreesAdminController@deleteCarrera')->name('degreeAdmin.deleteCarrera')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Moderación de Publicaciones
    Route::resource('postsMod', 'AdminPanel\PostsModController')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/aprobarTutPost/{id}', 'AdminPanel\PostsModController@aprobarTutPost')->name('postsMod.aprobarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarTutPost/{id}', 'AdminPanel\PostsModController@rechazarTutPost')->name('postsMod.rechazarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarHosPost/{id}', 'AdminPanel\PostsModController@aprobarHosPost')->name('postsMod.aprobarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarHosPost/{id}', 'AdminPanel\PostsModController@rechazarHosPost')->name('postsMod.rechazarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarCyVPost/{id}', 'AdminPanel\PostsModController@aprobarCyVPost')->name('postsMod.aprobarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarCyVPost/{id}', 'AdminPanel\PostsModController@rechazarCyVPost')->name('postsMod.rechazarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::get('/banned', function () {
      return view('auth.banned');
    });

web/app/Tutorias.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tutorias extends Model
{
  #referncia a la tabla que se va a utilizar
  protected $table = "tutorias";

  
}

web/app/Http/Controllers/TutoriasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\User;
use App\Tutorias;

class TutoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

      # llama la vista y trae todos datos de la tabla
      $datos = Tutorias::where('estadoPost','Aprobada')->orderBy('created_at','desc')->paginate(10);
      return view('clasificado.Tutorias.tutorias',compact('datos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function search(Request $request)
     {
        $search = $request->get('search');
        $datos = Tutorias::where('estadoPost','Aprobada')
          ->whereRaw('concat(titulo,materia,costo,ubicacion,codigoPost) like \'%' .$search .'%\' ')
          ->orderBy('created_at','desc')
          ->paginate(10);
        return view('clasificado.Tutorias.tutorias',compact('datos'));
     }
     public function create()
     {

     }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      #datos que van a la base de datos

      $this->validate($request,[
      'titulo' => 'required',
      'nombreTutor' => 'required',
      'materia' => 'required',
      'costo' => 'required',
      'ubicacion' => 'required',
      'descripcion' => 'required',
      'celular' => 'required',
       // 'imagen' => 'required',
  ]);

      $tutorias = new Tutorias () ;
      //Generación de Código de Publicación.
      $tutorias->codigoPost= 'TUT-' . (Tutorias::all()->max('id') + 1);
      $tutorias->titulo= $request->input('titulo');
      $tutorias->nombreTutor= $request->input('nombreTutor');
      $tutorias->materia= $request->input('materia');
      $tutorias->costo= $request->input('costo');
      $tutorias->ubicacion= $request->input('ubicacion');
      $tutorias->descripcion= $request->input('descripcion');
      $tutorias->celular= $request->input('celular');
      $tutorias->nombre =\Auth::user()->nombre;
      $tutorias->email =\Auth::user()->email;
      //
      if ($request->hasFile('imagen')) {
          $file = $request->file('imagen');
          $name_image = time().$file->getClientOriginalName();
          $file->move(public_path().'/imagenes/clasificados/tutorias',$name_image);
          $tutorias->imagen =$name_image;
      }

     #salvar en la base de datos
      $tutorias->save();

        return back()->with('success',' Tutoría: '.$tutorias->titulo.' Creada exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show($id)
     {
         $datosT = Tutorias::find($id);
         return view('Perfil.Tutorias.show2', compact('datosT'));
     }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
     {
         $datosT = Tutorias::find($id);
         return view('Perfil.Tutorias.detalles2', compact('datosT'));
     }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, $id)
     {

           $datosT = Tutorias::find($id);
           $datosT->titulo = $request->get('titulo');
           $datosT->nombreTutor = $request->get('nombreTutor');
           $datosT->materia = $request->get('materia');
           $datosT->costo = $request->get('costo');
           $datosT->ubicacion = $request->get('ubicacion');
           $datosT->descripcion = $request->get('descripcion');
           $datosT->celular = $request->get('celular');
           $datosT->estadoPost = ('En Moderación');

           if($request->hasFile('imagen')){
             if ($datosT->imagen === 'post-placeholder.jpg')
             {
             }else {
             unlink(public_path().'/imagenes/clasificados/tutorias/'.$datosT->imagen);
             }
             $file = $request->file('imagen');
             // ejemplo para guardar fotos encima de otra foto.
             $name_image = time().$file->getClientOriginalName();
             $file->move(public_path().'/imagenes/clasificados/tutorias/',$name_image);
             $datosT->imagen = $name_image;

           }
           $datosT->save();

         return redirect('/miPerfil')->with('success','Datos de la Tutoría Actualizados Exitosamente.');
       }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id)
     { $file = Tutorias::where('id', $id)->find($id);
       $usr = (auth()->user()->email);

       if ($usr ===$file->email)
       {
         if ($file->imagen === 'post-placeholder.jpg')
         {
         Tutorias::where('id', $id)->delete();
         return back()->with('success','Tutoría eliminada exitosamente.');
         }
        else {
          $file = Tutorias::where('id', $id)->find($id);
          if(unlink(public_path().'/imagenes/clasificados/tutorias/'.$file->imagen)){
           $file->delete();
           return back()->with('success','Tutoría eliminada exitosamente.');
              }
        }
       }
      }
}

web/resources/views/clasificado/Tutorias/detalle.blade.php
<div class="card-body" >
<h2 class="h2-responsive text-center"><strong>{{$tutoria->titulo}}</strong></h2> <br>
    <div class="text-center">
      <img style="max-height: 500px; max-width: 500px;" class="img-thumbnail shadow" src="/imagenes/clasificados/tutorias/{{$tutoria->imagen}}">
      <br><br>
      <h4 class="h4-responsive text-success"><strong>${{$tutoria->costo}}/Hora</h5></strong></h4>

    </div>



    <h6 class="h6-responsive"><i class="fas fa-chalkboard-teacher" style="font-size:20px;"></i> Tutor: {{$tutoria->nombreTutor}}</h6>
    <h6 class="h6-responsive"><i class="fas fa-heart" style="font-size:20px;"></i> Materia: {{$tutoria->materia}}</h6>
    <h6 class="h6-responsive heading"><i class="fas fa-map-marker-alt" style="font-size:20px;"></i> Ubicación: {{$tutoria->ubicacion}}</h6>
    <h6 class="h6-responsive"><i class="fas fa-info" style="font-size:20px;"></i> Descripción: {{$tutoria->descripcion}}</h6>
    <hr>

<!--Accordion wrapper-->
<div class="accordion md-accordion shadow" id="accordionEx" role="tablist" >
  <!-- Accordion card -->

    <!-- Card header -->
    <div class="card-header bg-info " role="tab" id="headingOne1">
      <a data-toggle="collapse" data-parent="#accordionEx" href="#collapscard" aria-expanded="true"
        aria-controls="collapsecard">
        <h6 class="mb-0 text-white ">
          <i class=" fas fa-angle-down rotate-icon"></i> Información de Contacto
        </h6>
      </a>
    </div>

    <!-- Card body -->
    <div id="collapscard" class="collapse show thumb-shadow" role="tabpanel" aria-labelledby="headingOne1"
      data-parent="#accordionEx">
      <div class="col-xs-12 col-lg-12 text-justify">
          <div class="card-body" >
        <label><i class="far fa-id-badge" style="font-size:20px;"></i>  Nombre del Contacto: {{$tutoria->nombre}}</label>
        <br>
        <label><i class="fas fa-mobile" style="font-size:20px;"></i>  Celular: {{$tutoria->celular}}</label>
        <br>
        <label><i class="fas fa-at" style="font-size:20px;"></i>  Email: {{$tutoria->email}}</label>
      </div>
      </div>
    </div>
  </div>
  <!-- Accordion card -->

  <hr>

      <p class="h5 bold-text">Información del contacto</p>
      <p><i class="fas fa-user" style="font-size:20px;"></i> Publicado por: <a href="{{route('perfil.verPerfil', $tutoria->email)}}"> {{$tutoria->email}}</a> </p>
      <p><i class="fas fa-ticket-alt" style="font-size:20px;"></i> Código de Publicación: {{$tutoria->codigoPost}}</p>
      <p><i class="fas fa-clock" style="font-size:20px;"></i> Publicado {{$tutoria->created_at->diffForHumans()}}</p>

<div class="modal-footer">
    <button type="submit" class="btn btn-success" data-dismiss="modal">Cerrar</button>
</div>
</div>

web/resources/views/clasificado/Tutorias/formulario.blade.php
<form action="{{ route('tutorias.store')}}" method="POST" enctype="multipart/form-data">
 @csrf
 <!-- Input de Titulo -->
        <div class="form-group row">
          <label for="titulo" class="col-form-label col-sm-3">Titulo:</label>
          <div class="col-sm-8">
            <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Titulo">
          </div>
        </div>

        <!-- Input de Nombre del tutor -->
            <div class="form-group row">
              <label for="nombreTutor" class="col-form-label col-sm-3">Nombre del Tutor:</label>
              <div class="col-sm-8">
                <input type="text" name="nombreTutor" id="nombreTutor" class="form-control" placeholder="Nombre del Tutor">
              </div>
            </div>

            <!-- Input de Materia -->
                 <div class="form-group row">
                   <label for="materia" class="col-form-label  col-sm-3 ">Materia:</label>
                   <div class="col-sm-8">
                   <select id="materia" class="form-control" name="materia" required>
                     <option disabled selected>---Escoja una materia---</option>
                       <option>Programación</option>
                       <option>Cálculo</option>
                       <option>Otros</option>
                   </select>
                   </div>
                   @if ($errors->has('sede'))
                       <span class="invalid-feedback" role="alert">
                           <strong>{{ $errors->first('sede') }}</strong>
                       </span>
                   @endif
               </div>

              <!-- Input de costo por hora -->
              <div class="form-group row">
                <label for="costo" class="col-form-label col-sm-3">Costo Por Hora:</label>
                <div class="col-sm-8">
                  <input type="number" name="costo" id="costo" class="form-control" min="0" max="9999" step="0.01" oninput="validity.valid||(value=)" placeholder="Costo">
                </div>
              </div>

                   <!-- Input de Ubicacion -->
                         <div class="form-group row">
                           <label for="ubicacion" class="col-form-label col-sm-3">Ubicación:</label>
                           <div class="col-sm-8">
                             <input type="text" name="ubicacion" id="ubicación" class="form-control" placeholder="Ubicación" >
                           </div>
                         </div>

                         <!-- Input de Descripción -->
                            <div class="form-group row">
                              <label for="descripcion" class="col-form-label col-sm-3">Descripción:</label>
                              <div class="col-sm-8">
                                <textarea class="form-control" id="message-text" name="descripcion" placeholder="Descripción"></textarea>
                              </div>
                            </div>

                            <!-- Input de Imagen -->
                            <div class="form-group row">
                               <label for="addfoto" class="col-form-label col-sm-3">Agregar Fotos:</label>
                               <div class="col-sm-8">
                               <input type="file" name="imagen" id="imagen" class="form-control" placeholder="Add Foto" >
                               </div>
                           </div>


  <!-- Informacion de Contacto -->
  <hr>
  <p class="h5">Información de Contacto:</p>

  <!-- Input de Celular -->
  <div class="form-group row">
    <label for="Celular" class="col-form-label col-sm-3">Celular:</label>
    <div class="col-sm-8">
      <input type="text" name="celular" id="celular" class="form-control" placeholder="Celular" tabindex="1">
    </div>
  </div>



  <!-- Modal Footer -->
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-success">Publicar</button>
  </div>

</form>

web/resources/views/clasificado/Tutorias/formularioUpdate.blade.php
<h2 class="h2-responsive text-center"><strong>{{$tutoria->titulo}} ({{$tutoria->codigoPost}})</strong></h2>
<form action="{{route('tutorias.update', $tutoria->id)}}" method="POST" enctype="multipart/form-data">
     @csrf
        <!-- Imagen actual del tutorias -->
        <div class="text-center">
            <img style="max-height: 400px; max-width: 400px;" class="img-thumbnail shadow" src="/imagenes/clasificados/tutorias/{{$tutoria->imagen}}">
        </div> <br>

        <!-- Nueva Imagen -->
        <div class="form-group row p-2">
         <label for="imagen" class="col-form-label col-sm-3 font-weight-bold">Nueva Imagen</label>
         <input type="file" class="form-control-file col-sm-8" id="imagen" name="imagen" accept="image/*">
       </div>

       <!-- Título -->
       <div class="form-group row">
          <label for="titulo" class="col-form-label col-sm-3">Título:</label>
          <div class="col-sm-8">
            <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Titulo" value="{{$tutoria->titulo}}">
          </div>
        </div>

        <!-- Nombre del tutor -->
        <div class="form-group row">
            <label for="nombreTutor" class="col-form-label col-sm-3">Nombre del Tutor:</label>
            <div class="col-sm-8">
                <input type="text" name="nombreTutor" id="nombreTutor" class="form-control" placeholder="Nombre del Tutor" value="{{$tutoria->nombreTutor}}">
            </div>
        </div>

        <!-- Input de Materia -->
        <div class="form-group row">
            <label for="materia" class="col-form-label  col-sm-3 ">Materia:</label>
            <div class="col-sm-8">
                <select id="tutoria_materia_{{$tutoria->id}}" class="form-control" name="materia" required>
                    <option>Programación</option>
                    <option>Física</option>
                    <option>Química</option>
                    <option>Cálculo</option>
                    <option>Otros</option>
                </select>
            </div>
        </div>

        <!-- Input de costo por hora -->
        <div class="form-group row">
            <label for="costo" class="col-form-label col-sm-3">Costo por Hora:</label>
            <div class="col-sm-8">
                <input type="number" name="costo" id="costo" class="form-control" min="0" max="9999" step="0.01" oninput="validity.valid||(value=)" placeholder="Costo" value="{{$tutoria->costo}}">
            </div>
        </div>

        <!-- Input de Ubicacion -->
        <div class="form-group row">
            <label for="ubicacion" class="col-form-label col-sm-3">Ubicación:</label>
            <div class="col-sm-8">
                <input type="text" name="ubicacion" id="ubicación" class="form-control" placeholder="Ubicación" value="{{$tutoria->ubicacion}}">
            </div>
        </div>

        <!-- Input de Descripción -->
        <div class="form-group row">
            <label for="descripcion" class="col-form-label col-sm-3">Descripción:</label>
            <div class="col-sm-8">
                <textarea class="form-control" id="message-text" name="descripcion" placeholder="Descripción">{{$tutoria->descripcion}}</textarea>
            </div>
        </div>

        <!-- Informacion de Contacto -->
  <hr>
  <p class="h5">Información de Contacto:</p>

  <!-- Input de Celular -->
  <div class="form-group row">
    <label for="Celular" class="col-form-label col-sm-3">Celular:</label>
    <div class="col-sm-8">
      <input type="text" name="celular" id="celular" class="form-control" placeholder="Celular" tabindex="1" value="{{$tutoria->celular}}">
    </div>
  </div>

  <!-- Modal Footer -->
  <div class="modal-footer">
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-success">Actualizar</button>
  </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#tutoria_materia_{{$tutoria->id}}').val('{{$tutoria->materia}}').change();
        });
    </script>

</form>

web/resources/views/clasificado/Tutorias/tutoria.blade.php
<div class="container">
    <div class="row">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded card ">
                <div class="card-body d-flex ">
                    <div class="col-md-8 px-3 ">
                        <h3 class="card-title  ">{{$tutoria->titulo}}</h3>
                        <h5 class="card-text font-weight-bold"><i class="fas fa-book"></i> {{$tutoria->materia}}</h5>
                        <p class="card-text"><i class="fas fa-map-marker-alt"></i> {{$tutoria->ubicacion}}</p>
                        <p class="card-text"><i class="fas fa-info"></i> {{$tutoria->descripcion}}</p>
                        <p class="card-text"><i class="fas fa-clock"></i> {{$tutoria->created_at->diffForHumans()}}</p>
                        @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Ver más Detalles','id_modal'=>'anu'.$id,'title'=>'DETALLES DE LA TUTORÍA','vista'=>'clasificado.Tutorias.detalle'])
                    </div>
                    <div class="text-right view view-cascade overlay"  width="500px">
                        <img class="card-img-top shadow" src="/imagenes/clasificados/tutorias/{{$tutoria->imagen}}"
                        class="pull-left img-responsive thumb margin10 img-thumbnail rounded">
                        <a>
                            <div class="mask rgba-white-slight"></div>

                          </a>
                          <br>
                            <h5 class="card-center text-success font-weight-bold">${{$tutoria->costo}}</h5>


                    </div>
                </div>
            </div>
    </div>
</div>

web/resources/views/clasificado/Tutorias/tutorias.blade.php
@extends('layouts.app')
@section('content')
 <!-- Back to top -->
 @include('Homes.BacktoTop')

<!--Jumbotron -->
<div class="jumbotron jumbotron-fluid  ">
  <div class="container">
    <h1 class="display-4">Sección de Tutorías</h1>
    <p class="lead">Aquí tendrás acceso a tutorías, de diversas materias.</p>
  </div>
</div>
<div class="container">
    @if(count($errors) > 0)
      <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
              <li>{{$error}}</li>
            @endforeach
        </ul>
      </div>
    @endif
    <!-- Formulario de Búsqueda -->

    <form action="{{route('tutorias.search')}}" method="get">
      <div class="form-group row justify-content-center">
        <div class="col-auto">
          <input class="form-control form-control" type="search" placeholder="Buscar Tutoría" aria-label="Search" name="search" >
        </div>

        <div class="col-auto">
            <button class="btn btn-success col" type="submit"> <i class="fas fa-search"></i> </button>
        </div>
      </div>
    </form>

    <div class="text-center">
        @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Agregar Tutoría','id_modal'=>'mod1','title'=>'AGREGA TUTORIAS AQUI','vista'=>'clasificado.Tutorias.formulario'])
    </div>

     <br>

    <div id="anuncios" class="row justify-content-center">
        <div class="col-md-8">
              @isset($datos)
                  <!-- Paginación de publicaciones -->
                  <div class="pagination justify-content-center">
                      {{ $datos->links() }}
                  </div>
                  @if($datos->count() > 0)
                    @foreach ($datos as $tutoria)
                      @include('clasificado.Tutorias.tutoria', $tutoria)                 
                    @endforeach
                  @else
                    <div class="alert alert-info text-center" role="alert">
                      No existen anuncios de tutorías publicados en estos momentos.
                    </div>
                  @endif
                  
                  <!-- Paginación de publicaciones -->
                  <div class="pagination justify-content-center">
                      {{ $datos->links() }}
                  </div>
              @endisset
        </div>
    </div> <br>

</div>

@endsection