web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Activación del controlador de verificación de correo
Auth::routes(['verify' => true]);

//Ruta de Página principal
Route::resource('/', 'HomeController')->middleware(['checkUserStatus']);

//Ruta de perfil de usuario
Route::resource('miPerfil', 'PerfilController');
//Rutas para el crud de anuncios
Route::get('Perfil/Compraventa/show/{id}', 'AnunciosController@show')->name('Perfil.show');
Route::get('Perfil/Compraventa/detalles/{id}', 'AnunciosController@edit')->name('Perfil.detalles')->middleware(['auth']);
Route::post ('Perfil/update/{id}', 'AnunciosController@update')->name('Perfil.update')->middleware(['auth']);
Route::get('dts/{id}', 'AnunciosController@destroy')->name('dts');
//Rutas para el crud de tutorias
Route::get('Perfil/show2/{id}', 'TutoriasController@show')->name('Perfil.show2');
Route::get('Perfil/detalles2/{id}', 'TutoriasController@edit')->name('Perfil.detalles2')->middleware(['auth']);
Route::put ('Perfil/update2/{id}', 'TutoriasController@update')->name('Perfil.update2')->middleware(['auth']);
Route::get('dt/{id}', 'TutoriasController@destroy')->name('dt');
//Rutas para el crud de Bolsa de trabajo
Route::get('dB/{id}', 'BolsatrabajoController@destroy')->name('dtB');
//Rutas para el crud de Eventos
Route::get('Perfil/showE/{id}', 'EventoController@show')->name('Perfil.showE');
Route::get('Perfil/detallesE/{id}', 'EventoController@edit')->name('Perfil.detallesE')->middleware(['auth']);
Route::get('dE/{id}', 'EventoController@destroy')->name('dtE');
//Rutas para el crud de Alquiler y Hospedaje
Route::get('Perfil/showH/{id}', 'HospedajeController@show')->name('Perfil.showH');
Route::get('Perfil/detallesH/{id}', 'HospedajeController@edit')->name('Perfil.detallesH')->middleware(['auth']);
Route::put ('Perfil/updateH/{id}', 'HospedajeController@update')->name('Perfil.updateH')->middleware(['auth']);
Route::get('dtH/{id}', 'HospedajeController@destroy')->name('dtH');


//ruta para cargar carreras al formulario de editar el perfil
Route::get('miPerfil/getcarreras/{id}','PerfilController@getCarreras');
//Ruta de Actualización de Perfil
Route::post('miPerfil/updateProfile', 'PerfilController@updateProfile')->name('perfil.update')->middleware(['auth']);
//Ruta para mostrar los perfiles de los usuarios
Route::get('usuario/{email}', 'PerfilController@verPerfil')->name('perfil.verPerfil')->middleware(['auth','checkUserStatus']);
//Ruta de registro
Route::get('/register','RegistroController@getFacultades')->name('register');
Route::get('register/getcarreras/{id}','RegistroController@getCarreras');



//Rutas de Clasificados
Route::group(['prefix' => 'clasificado'], function () {
//Rutas de Compras/Ventas
Route::resource('anuncios','AnunciosController');
Route::get('/anuncios','AnunciosController@search')->name('anuncios.search');
Route::post('anuncios/update/{id}', 'AnunciosController@update')->name('anuncios.update')->middleware(['auth']);

//Ruta de tutorias
Route::resource('tutorias', 'TutoriasController');
Route::get('/tutorias','TutoriasController@search')->name('tutorias.search');
Route::post('tutorias/update/{id}', 'TutoriasController@update')->name('tutorias.update')->middleware(['auth']);

//Ruta de alquilerhospedaje
Route::resource('alquilerhospedajes', 'HospedajeController');
Route::get('/alquilerhospedajes','HospedajeController@search')->name('alquilerhospedajes.search');
Route::post('alquilerhospedajes/update/{id}', 'HospedajeController@update')->name('alquilerhospedajes.update')->middleware(['auth']);

});
//Ruta de bolsatrabajo
Route::resource('bolsatrabajos', 'BolsatrabajoController');
Route::get('bolsatrabajos','BolsatrabajoController@search')->name('bolsaDeTrabajo.search');
Route::post('bolsatrabajos/update/{id}', 'BolsatrabajoController@update')->name('bolsaDetrabajo.update')->middleware(['auth']);

//Ruta de Eventos
Route::resource('eventos','EventoController');
Route::get('/eventos','EventoController@searchE');
Route::post('eventos/update/{id}', 'EventoController@update')->name('eventos.update')->middleware(['auth']);

//Route::resource('eventos','EventoController@carga')->name('eventos');


## Rutas del panel de administración ##
    //Rutas de Gestión de Usuarios
    Route::get('usersAdmin/getUser/', 'AdminPanel\UsersAdminController@getUser')->name('usersAdmin.getUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/changeRole/{email}', 'AdminPanel\UsersAdminController@changeRole')->name('usersAdmin.changeRole')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/banUser/{email}', 'AdminPanel\UsersAdminController@banUser')->name('usersAdmin.banUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/reactivateUser/{email}', 'AdminPanel\UsersAdminController@reactivateUser')->name('usersAdmin.reactivateUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::resource('usersAdmin', 'AdminPanel\UsersAdminController')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Gestión de Facultades y Carreras
    Route::resource('degreesAdmin', 'AdminPanel\DegreesAdminController')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newFacultad', 'AdminPanel\DegreesAdminController@newFacultad')->name('degreeAdmin.newFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editFacultad/{id}', 'AdminPanel\DegreesAdminController@editFacultad')->name('degreeAdmin.editFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteFacultad/{id}', 'AdminPanel\DegreesAdminController@deleteFacultad')->name('degreeAdmin.deleteFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newCarrera/{id}', 'AdminPanel\DegreesAdminController@newCarrera')->name('degreeAdmin.newCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editCarrera/{id}', 'AdminPanel\DegreesAdminController@editCarrera')->name('degreeAdmin.editCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteCarrera/{id}', 'AdminPanel\DegreesAdminController@deleteCarrera')->name('degreeAdmin.deleteCarrera')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Moderación de Publicaciones
    Route::resource('postsMod', 'AdminPanel\PostsModController')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/aprobarTutPost/{id}', 'AdminPanel\PostsModController@aprobarTutPost')->name('postsMod.aprobarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarTutPost/{id}', 'AdminPanel\PostsModController@rechazarTutPost')->name('postsMod.rechazarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarHosPost/{id}', 'AdminPanel\PostsModController@aprobarHosPost')->name('postsMod.aprobarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarHosPost/{id}', 'AdminPanel\PostsModController@rechazarHosPost')->name('postsMod.rechazarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarCyVPost/{id}', 'AdminPanel\PostsModController@aprobarCyVPost')->name('postsMod.aprobarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarCyVPost/{id}', 'AdminPanel\PostsModController@rechazarCyVPost')->name('postsMod.rechazarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::get('/banned', function () {
      return view('auth.banned');
    });

web/app/Bolsatrabajo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bolsatrabajo extends Model
{
  #referncia a la tabla que se va a utilizar
  protected $table = "bolsatrabajo";
  }

web/app/Http/Controllers/BolsatrabajoController.php
<?php

namespace App\Http\Controllers;

use App\Bolsatrabajo;
use Illuminate\Http\Request;

class BolsatrabajoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      # llama la vista y trae todos datos de la tabla
      $datos = Bolsatrabajo::orderBy('created_at','desc')->paginate(10);
      return view('Bolsatrabajos.bolsatrabajos',compact('datos'));
    }

    public function search(Request $request)
     {
         $search = $request->get('search');
        $datos = Bolsatrabajo::whereRaw('concat(codigoPost,titulo,ubicacion,empresa,salario,beneficio) like \'%' .$search .'%\' ')
                                ->orderBy('created_at','desc')
                                ->paginate(10);
        return view('Bolsatrabajos.bolsatrabajos',compact('datos'));
     }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        #datos que van a la base de datos

        $this->validate($request,[
        'urgente' => 'required',
        'titulo' => 'required',
        'ubicacion' => 'required',
        'empresa' => 'required',
        'tipoPuesto' => 'required',
        'salario' => 'required',
        'direccion' => 'required',
        'descripcion' => 'required',
        'habilidades' => 'required',
        'fecha' => 'required',
        'beneficio' => 'required',
        'nombreContacto' => 'required',
        'celular' => 'required',
        'emailContacto' => 'required',
        // 'imagen' => 'required',
    ]);





        $bolsatrabajo = new Bolsatrabajo();
        //Generación de Código de Publicación.
        $bolsatrabajo->codigoPost = 'BDT-' . (Bolsatrabajo::all()->max('id') + 1);
        $bolsatrabajo->urgente= $request->input('urgente');
        $bolsatrabajo->titulo= $request->input('titulo');
        $bolsatrabajo->ubicacion= $request->input('ubicacion');
        $bolsatrabajo->empresa= $request->input('empresa');
        $bolsatrabajo->tipoPuesto= $request->input('tipoPuesto');
        $bolsatrabajo->salario= $request->input('salario');
        $bolsatrabajo->direccion= $request->input('direccion');
        $bolsatrabajo->descripcion= $request->input('descripcion');
        $bolsatrabajo->habilidades= $request->input('habilidades');
        $bolsatrabajo->fecha= $request->input('fecha');
        $bolsatrabajo->beneficio= $request->input('beneficio');
        $bolsatrabajo->email = \Auth::user()->email;
        $bolsatrabajo->nombreContacto= $request->input('nombreContacto');
        $bolsatrabajo->celular= $request->input('celular');
        $bolsatrabajo->emailContacto= $request->input('emailContacto');


        #salvar en la base de datos


      if ($request->hasFile('imagen')) {
          $file = $request->file('imagen');
          $name_image = time().$file->getClientOriginalName();
          $file->move(public_path().'/imagenes/bolsatrabajo',$name_image);
          $bolsatrabajo->imagen =$name_image;
      }
      $bolsatrabajo->save();
      return back()->with('success','Anuncio de Empleo creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bolsatrabajo  $bolsatrabajo
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $datosB = Bolsatrabajo::find($id);
      return view('Perfil.Bolsatrabajo.show', compact('datosB'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bolsatrabajo  $bolsatrabajo
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $datosB = Bolsatrabajo::find($id);
      return view('Perfil.Bolsatrabajo.detalles', compact('datosB'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bolsatrabajo  $bolsatrabajo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $bolsatrabajo = Bolsatrabajo::find($id);

          $bolsatrabajo->urgente= $request->input('urgente');
          $bolsatrabajo->titulo= $request->input('titulo');
          $bolsatrabajo->ubicacion= $request->input('ubicacion');
          $bolsatrabajo->empresa= $request->input('empresa');
          $bolsatrabajo->tipoPuesto= $request->input('tipoPuesto');
          $bolsatrabajo->salario= $request->input('salario');
          $bolsatrabajo->direccion= $request->input('direccion');
          $bolsatrabajo->descripcion= $request->input('descripcion');
          $bolsatrabajo->habilidades= $request->input('habilidades');
          $bolsatrabajo->fecha= $request->input('fecha');
          $bolsatrabajo->beneficio= $request->input('beneficio');
          $bolsatrabajo->email = \Auth::user()->email;
          $bolsatrabajo->nombreContacto= $request->input('nombreContacto');
          $bolsatrabajo->celular= $request->input('celular');
          $bolsatrabajo->emailContacto= $request->input('emailContacto');

          if($request->hasFile('imagen')){
            if ($bolsatrabajo->imagen === 'post-placeholder.jpg')
            {
            }else {
            unlink(public_path().'/imagenes/bolsatrabajo/'.$bolsatrabajo->imagen);
            }
            $file = $request->file('imagen');
            $name_image = time().$file->getClientOriginalName();
            $file->move(public_path().'/imagenes/bolsatrabajo/',$name_image);
            $bolsatrabajo->imagen = $name_image;

          }

          $bolsatrabajo->save();
          return redirect('/miPerfil')->with('success','Anuncio de Empleo Actualizado Exitosamente.');
      }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bolsatrabajo  $bolsatrabajo
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { $file = Bolsatrabajo::where('id', $id)->find($id);
      $usr = (auth()->user()->email);

      if ($usr ===$file->email)
      {
        if ($file->imagen === 'post-placeholder.jpg')
        {
        Bolsatrabajo::where('id', $id)->delete();
        return back()->with('success','Anuncio de trabajo eliminado exitosamente.');
        }
       else {
         $file = Bolsatrabajo::where('id', $id)->find($id);
         if(unlink(public_path().'/imagenes/bolsatrabajo/'.$file->imagen)){
          $file->delete();
          return back()->with('success','Anuncio de trabajo eliminado exitosamente.');
             }
       }
      }
     }

}

web/resources/views/Bolsatrabajos/bolsatrabajo.blade.php
<div class="container">
    <div class="row">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded card ">
                <div class="card-body d-flex ">
                    <div class="col-md-8 px-3 ">
                        <h3 class="card-title">{{$bolsatrabajo->titulo}}</h3>
                        <p class="card-text"><i class="fas fa-building"></i> {{$bolsatrabajo->empresa}}</p>
                        <p class="card-text"><i class="fas fa-map-marker-alt"></i> {{$bolsatrabajo->ubicacion}}</p>   
                        <p class="card-text"><i class="fas fa-file-contract"></i> {{$bolsatrabajo->tipoPuesto}}</p>  
                        <p class="card-text"><i class="fas fa-location-arrow"></i> {{$bolsatrabajo->direccion}}</p>                           
                        <p class="card-text"><i class="fas fa-clock"></i> Publicado {{$bolsatrabajo->created_at->diffForHumans()}}</p>                                           
                        @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Ver más Detalles','id_modal'=>'anun'.$id,'title'=>'Detalle Bolsa de Trabajo','vista'=>'Bolsatrabajos.detalle'])

                    </div>
                    <div class="text-right view view-cascade overlay"  width="500px">
                        <img class="card-img-top shadow" src="/imagenes/bolsatrabajo/{{$bolsatrabajo->imagen}}"
                        class="pull-left img-responsive thumb margin10 img-thumbnail rounded">
                        <a>
                            <div class="mask rgba-white-slight"></div>
                            
                          </a>
                          <br>  
                          <h5 class="card-center text-success font-weight-bold text-right">Salario: ${{$bolsatrabajo->salario}}</h5>
                          @if($bolsatrabajo->urgente === "Sí")
                            <h5 class="card-center text-danger font-weight-bold text-right">Urgente</h5>
                          @endif
                    </div>
                </div>
            </div>
    </div>
</div>

web/resources/views/Bolsatrabajos/bolsatrabajos.blade.php
@extends('layouts.app')
@section('content')
 <!-- Back to top -->        
 @include('Homes.BacktoTop')

<!--Jumbotron -->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Sección de Bolsa de Trabajo</h1>
    <p class="lead">Aquí podrás encontrar oportunidades de empleo con las empresas más prestigiosas de la región.</p>
  </div>
</div>

<div class="container">    
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

    <!-- Formulario de Búsqueda -->
    <form action="{{route('bolsaDeTrabajo.search')}}" method="get">
        <div class="form-group row justify-content-center">         
            <div class="col-auto">
            <input class="form-control form-control" type="search" placeholder="Buscar Vacante" aria-label="Search" name="search" >
            </div>    

            <div class="col-auto">
                <button class="btn btn-success col" type="submit"> <i class="fas fa-search"></i> </button> 
            </div> 
        </div>                      
    </form>  
    
    @if(auth()->check() && ( auth()->user()->hasAnyRole('Administrador') || auth()->user()->hasAnyRole('Moderador') ) )
    <div class="text-center"> 
        @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Agregar Empleo','id_modal'=>'mod1','title'=>'AGREGA EMPLEOS AQUI','vista'=>'Bolsatrabajos.formulario'])
    </div> 
    @endif
  <br>
        <div id="tutorias" class="row justify-content-center">
            <div class="col-md-8"> 
                 <!-- Paginación de publicaciones -->
                 <div class="pagination justify-content-center">
                    {{ $datos->links() }}       
                </div>

                 @isset($datos)
                    @if($datos->count() > 0)
                        @foreach ($datos as $bolsatrabajo)                    
                            @include('Bolsatrabajos.bolsatrabajo', $bolsatrabajo)                    
                        @endforeach
                    @else
                        <div class="alert alert-info text-center" role="alert">
                            No existen anuncios de vacantes publicados en estos momentos.
                        </div>
                    @endif
                     <!-- Paginación de publicaciones -->
                    <div class="pagination justify-content-center">
                        {{ $datos->links() }}       
                    </div>
                 @endisset                
            </div>
        </div>

</div>

@endsection

web/resources/views/Bolsatrabajos/formulario.blade.php
<form action="{{ route('bolsatrabajos.store')}}" method="POST" enctype="multipart/form-data">
 @csrf

 <!-- Input de  Urgente -->
<div class="col-form-label col-sm-3 ">
<label class="badge badge-primary">Urgente ? </label><br>
<label class="form-check-label" for="urgente"> Si </label>
<div class="form-check form-check-inline">
<input class="form-check-input" type="radio" name="urgente" id="Si" value="Sí" required>
 </div>
 <label class="form-check-label" for="urgente"> No </label>
 <div class="form-check form-check-inline">
     <input class="form-check-input" type="radio" name="urgente" id="No" value="No" required>
</div>
 </div>
 <!-- Input de Titulo -->
        <div class="form-group row">
          <label for="titulo" class="col-form-label col-sm-3">Titulo:</label>
          <div class="col-sm-8">
            <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Titulo" required>
          </div>
        </div>

        <!-- Input de Ubicacion -->
              <div class="form-group row">
                <label for="ubicacion" class="col-form-label col-sm-3">Ubicación:</label>
                <div class="col-sm-8">
                  <input type="text" name="ubicacion" id="ubicacion" class="form-control" placeholder="Ubicación" required >
                </div>
              </div>

        <!-- Input de Empresa -->
            <div class="form-group row">
              <label for="empresa" class="col-form-label col-sm-3">Empresa:</label>
              <div class="col-sm-8">
                <input type="text" name="empresa" id="empresa" class="form-control" placeholder="Empresa" required>
              </div>
            </div>

            <!-- Input de M -->
                 <div class="form-group row">
                   <label for="tipoPuesto" class="col-form-label  col-sm-3 ">Tipo de Puesto:</label>
                   <div class="col-sm-8">
                   <select id="tipoPuesto" class="form-control" name="tipoPuesto" required>
                       <option>Tiempo Completo</option>
                       <option>Tiempo Parcial</option>
                       <option>Contrato/Temporario</option>
                   </select>
                   </div>
                   @if ($errors->has('sede'))
                       <span class="invalid-feedback" role="alert">
                           <strong>{{ $errors->first('sede') }}</strong>
                       </span>
                   @endif
               </div>
  <hr>
  <p class="h5">Detalles:</p>
               <!-- Input de costo por hora -->
                   <div class="form-group row">
                     <label for="salario" class="col-form-label col-sm-3">Salario Estimado:</label>
                     <div class="col-sm-8">
                       <input type="number" name="salario" id="salario" class="form-control"  min="1" max="10000" step="1" oninput="validity.valid||(value=)" placeholder="Salario" required>
                     </div>
                   </div>

                   <!-- Input de Direccion -->
                    <div class="form-group row">
                        <label for="direccion" class="col-form-label col-sm-3">Dirección:</label>
                        <div class="col-sm-8">
                        <textarea class="form-control" id="message-text" name="direccion" placeholder="Direccion"></textarea>
                          </div>
                    </div>
                    <!-- Input de Descripcion -->
                     <div class="form-group row">
                         <label for="descripcion" class="col-form-label col-sm-3">Descripción:</label>
                         <div class="col-sm-8">
                         <textarea class="form-control" id="message-text" name="descripcion" placeholder="Descripcion"></textarea>
                           </div>
                     </div>
                     <!-- Input de Habilidades -->
                      <div class="form-group row">
                          <label for="habilidades" class="col-form-label col-sm-3">Habilidades:</label>
                          <div class="col-sm-8">
                          <textarea class="form-control" id="message-text" name="habilidades" placeholder="Habilidades"></textarea>
                            </div>
                      </div>
                      <!-- Input de Fecha y Hora -->
                            <div class="form-group row">
                              <label for="fecha" class="col-form-label col-sm-3">Fecha:</label>
                              <div class="col-sm-8">
                                <input type="date" name="fecha" id="fecha" class="form-control" placeholder="00/00/0000" required >
                              </div>
                            </div>
                      <!-- Input de Beneficios-->
                       <div class="form-group row">
                           <label for="beneficio" class="col-form-label col-sm-3">Beneficios:</label>
                           <div class="col-sm-8">
                           <textarea class="form-control" id="message-text" name="beneficio" placeholder="Beneficios"></textarea>
                             </div>
                       </div>

                       <!-- Input de Imagen -->
                            <div class="form-group row">
                               <label for="addfoto" class="col-form-label col-sm-3">Agregar Fotos:</label>
                               <div class="col-sm-8">
                               <input type="file" name="imagen" id="imagen" class="form-control" placeholder="Add Foto" >
                               </div>
                           </div>
  <!-- Informacion de Contacto -->
  <hr>
  <p class="h5">Información de Contacto:</p>
  <!-- Input de Nombre del Contacto -->
         <div class="form-group row">
           <label for="nombreContacto" class="col-form-label col-sm-3">Nombre Contacto:</label>
           <div class="col-sm-8">
             <input type="text" name="nombreContacto" id="nombreContacto" class="form-control" placeholder="Nombre del Contacto">
           </div>
         </div>
  <!-- Input de Celular -->
  <div class="form-group row">
    <label for="Celular" class="col-form-label col-sm-3">Celular:</label>
    <div class="col-sm-8">
      <input type="text" name="celular" id="celular" class="form-control" placeholder="Celular" >
    </div>
  </div>
  <!-- Input de email -->
  <div class="form-group row">
    <label for="Email" class="col-form-label col-sm-3">Email:</label>
    <div class="col-sm-8">
      <input type="text" name="emailContacto" id="emailContacto" class="form-control" placeholder="Email">
    </div>
  </div>

  <!-- Modal Footer -->
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-success">Publicar</button>
  </div>
</form>