web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Activación del controlador de verificación de correo
Auth::routes(['verify' => true]);

//Ruta de Página principal
Route::resource('/', 'HomeController')->middleware(['checkUserStatus']);

//Ruta de perfil de usuario
Route::resource('miPerfil', 'PerfilController');
//Rutas para el crud de anuncios
Route::get('Perfil/Compraventa/show/{id}', 'AnunciosController@show')->name('Perfil.show');
Route::get('Perfil/Compraventa/detalles/{id}', 'AnunciosController@edit')->name('Perfil.detalles')->middleware(['auth']);
Route::post ('Perfil/update/{id}', 'AnunciosController@update')->name('Perfil.update')->middleware(['auth']);
Route::get('dts/{id}', 'AnunciosController@destroy')->name('dts');
//Rutas para el crud de tutorias
Route::get('Perfil/show2/{id}', 'TutoriasController@show')->name('Perfil.show2');
Route::get('Perfil/detalles2/{id}', 'TutoriasController@edit')->name('Perfil.detalles2')->middleware(['auth']);
Route::put ('Perfil/update2/{id}', 'TutoriasController@update')->name('Perfil.update2')->middleware(['auth']);
Route::get('dt/{id}', 'TutoriasController@destroy')->name('dt');
//Rutas para el crud de Bolsa de trabajo
Route::get('dB/{id}', 'BolsatrabajoController@destroy')->name('dtB');
//Rutas para el crud de Eventos
Route::get('Perfil/showE/{id}', 'EventoController@show')->name('Perfil.showE');
Route::get('Perfil/detallesE/{id}', 'EventoController@edit')->name('Perfil.detallesE')->middleware(['auth']);
Route::get('dE/{id}', 'EventoController@destroy')->name('dtE');
//Rutas para el crud de Alquiler y Hospedaje
Route::get('Perfil/showH/{id}', 'HospedajeController@show')->name('Perfil.showH');
Route::get('Perfil/detallesH/{id}', 'HospedajeController@edit')->name('Perfil.detallesH')->middleware(['auth']);
Route::put ('Perfil/updateH/{id}', 'HospedajeController@update')->name('Perfil.updateH')->middleware(['auth']);
Route::get('dtH/{id}', 'HospedajeController@destroy')->name('dtH');


//ruta para cargar carreras al formulario de editar el perfil
Route::get('miPerfil/getcarreras/{id}','PerfilController@getCarreras');
//Ruta de Actualización de Perfil
Route::post('miPerfil/updateProfile', 'PerfilController@updateProfile')->name('perfil.update')->middleware(['auth']);
//Ruta para mostrar los perfiles de los usuarios
Route::get('usuario/{email}', 'PerfilController@verPerfil')->name('perfil.verPerfil')->middleware(['auth','checkUserStatus']);
//Ruta de registro
Route::get('/register','RegistroController@getFacultades')->name('register');
Route::get('register/getcarreras/{id}','RegistroController@getCarreras');



//Rutas de Clasificados
Route::group(['prefix' => 'clasificado'], function () {
//Rutas de Compras/Ventas
Route::resource('anuncios','AnunciosController');
Route::get('/anuncios','AnunciosController@search')->name('anuncios.search');
Route::post('anuncios/update/{id}', 'AnunciosController@update')->name('anuncios.update')->middleware(['auth']);

//Ruta de tutorias
Route::resource('tutorias', 'TutoriasController');
Route::get('/tutorias','TutoriasController@search')->name('tutorias.search');
Route::post('tutorias/update/{id}', 'TutoriasController@update')->name('tutorias.update')->middleware(['auth']);

//Ruta de alquilerhospedaje
Route::resource('alquilerhospedajes', 'HospedajeController');
Route::get('/alquilerhospedajes','HospedajeController@search')->name('alquilerhospedajes.search');
Route::post('alquilerhospedajes/update/{id}', 'HospedajeController@update')->name('alquilerhospedajes.update')->middleware(['auth']);

});
//Ruta de bolsatrabajo
Route::resource('bolsatrabajos', 'BolsatrabajoController');
Route::get('bolsatrabajos','BolsatrabajoController@search')->name('bolsaDeTrabajo.search');
Route::post('bolsatrabajos/update/{id}', 'BolsatrabajoController@update')->name('bolsaDetrabajo.update')->middleware(['auth']);

//Ruta de Eventos
Route::resource('eventos','EventoController');
Route::get('/eventos','EventoController@searchE');
Route::post('eventos/update/{id}', 'EventoController@update')->name('eventos.update')->middleware(['auth']);

//Route::resource('eventos','EventoController@carga')->name('eventos');


## Rutas del panel de administración ##
    //Rutas de Gestión de Usuarios
    Route::get('usersAdmin/getUser/', 'AdminPanel\UsersAdminController@getUser')->name('usersAdmin.getUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/changeRole/{email}', 'AdminPanel\UsersAdminController@changeRole')->name('usersAdmin.changeRole')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/banUser/{email}', 'AdminPanel\UsersAdminController@banUser')->name('usersAdmin.banUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/reactivateUser/{email}', 'AdminPanel\UsersAdminController@reactivateUser')->name('usersAdmin.reactivateUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::resource('usersAdmin', 'AdminPanel\UsersAdminController')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Gestión de Facultades y Carreras
    Route::resource('degreesAdmin', 'AdminPanel\DegreesAdminController')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newFacultad', 'AdminPanel\DegreesAdminController@newFacultad')->name('degreeAdmin.newFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editFacultad/{id}', 'AdminPanel\DegreesAdminController@editFacultad')->name('degreeAdmin.editFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteFacultad/{id}', 'AdminPanel\DegreesAdminController@deleteFacultad')->name('degreeAdmin.deleteFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newCarrera/{id}', 'AdminPanel\DegreesAdminController@newCarrera')->name('degreeAdmin.newCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editCarrera/{id}', 'AdminPanel\DegreesAdminController@editCarrera')->name('degreeAdmin.editCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteCarrera/{id}', 'AdminPanel\DegreesAdminController@deleteCarrera')->name('degreeAdmin.deleteCarrera')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Moderación de Publicaciones
    Route::resource('postsMod', 'AdminPanel\PostsModController')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/aprobarTutPost/{id}', 'AdminPanel\PostsModController@aprobarTutPost')->name('postsMod.aprobarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarTutPost/{id}', 'AdminPanel\PostsModController@rechazarTutPost')->name('postsMod.rechazarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarHosPost/{id}', 'AdminPanel\PostsModController@aprobarHosPost')->name('postsMod.aprobarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarHosPost/{id}', 'AdminPanel\PostsModController@rechazarHosPost')->name('postsMod.rechazarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarCyVPost/{id}', 'AdminPanel\PostsModController@aprobarCyVPost')->name('postsMod.aprobarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarCyVPost/{id}', 'AdminPanel\PostsModController@rechazarCyVPost')->name('postsMod.rechazarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::get('/banned', function () {
      return view('auth.banned');
    });

web/resources/views/clasificado/Hospedador/alquilerhospedaje.blade.php
<div class="container">
        <div class="row">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded card ">
                    <div class="card-body d-flex ">
                        <div class="col-md-8 px-3 ">
                            <h3 class="card-title  ">{{$alquilerhosp->titulo}}</h3>
                            <p class="card-text"><i class="fas fa-map-marker-alt"></i> {{$alquilerhosp->ubicacion}}</p>
                            <p class="card-text"><i class="fas fa-info"></i> {{$alquilerhosp->descripcion}}</p>
                            <p class="card-text"><i class="fas fa-clock"></i> {{$alquilerhosp->created_at->diffForHumans()}}</p>
                            <p class="card-text">
                                @if($alquilerhosp->estacionamiento === "Sí")
                                    <i class="fas fa-parking"></i>
                                @endif
                                @if($alquilerhosp->amueblado === "Sí")
                                    <i class="fas fa-couch"></i>
                                @endif
                            </p>
                            @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Ver más Detalles','id_modal'=>'anun'.$id,'title'=>'ALQUILER/HOSPEDAJE ','vista'=>'clasificado.Hospedador.detalle'])
                       
                        </div>
                        <div class="text-right view view-cascade overlay"  width="500px">
                            <img class="card-img-top shadow" src="/imagenes/clasificados/hospedador/{{$alquilerhosp->imagen}}" 
                            class="pull-left img-responsive thumb margin10 img-thumbnail rounded">
                            <a>
                                <div class="mask rgba-white-slight"></div>
                                
                              </a>
                              <br>  
                                <h5 class="card-center text-success font-weight-bold">${{$alquilerhosp->precio}}/Mes</h5>
                                
    
                        </div>
                    </div>
                </div>
        </div>
    </div>

web/resources/views/clasificado/Hospedador/alquilerhospedajes.blade.php
@extends('layouts.app')
@section('content')
 <!-- Back to top -->
 @include('Homes.BacktoTop')

<!--Jumbotron -->
<div class="jumbotron jumbotron-fluid  ">
  <div class="container">
    <h1 class="display-4">Sección de Alquiler/Hospedaje</h1>
    <p class="lead">Aquí podrás encontrar cuartos o apartamentos en alquiler.</p>
  </div>
</div>
<div class="container">
    @if(count($errors) > 0)
      <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
              <li>{{$error}}</li>
            @endforeach
        </ul>
      </div>
    @endif
    <!-- Formulario de Búsqueda -->

    <form action="{{route('alquilerhospedajes.search')}}" method="get">
      <div class="form-group row justify-content-center">
        <div class="col-auto">
          <input class="form-control form-control" type="search" placeholder="Buscar Hospedaje" aria-label="Search" name="search" >
        </div>

        <div class="col-auto">
            <button class="btn btn-success col" type="submit"> <i class="fas fa-search"></i> </button>
        </div>
      </div>
    </form>

    <div class="text-center">
            @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Agregar Anuncio','id_modal'=>'mod1','title'=>'AGREGA TU ANUNCIO','vista'=>'clasificado.Hospedador.formulario'])
    </div>

     <br>

    <div id="anuncios" class="row justify-content-center">
        <div class="col-md-8">
              @isset($datos)
                  <!-- Paginación de publicaciones -->
                  <div class="pagination justify-content-center">
                      {{ $datos->links() }}
                  </div>
                  @if($datos->count() > 0)
                    @foreach ($datos as $alquilerhosp)
                      @include('clasificado.Hospedador.alquilerhospedaje', $alquilerhosp)              
                    @endforeach
                  @else
                    <div class="alert alert-info text-center" role="alert">
                      No existen anuncios de alquileres publicados en estos momentos.
                    </div>
                  @endif
                  
                  <!-- Paginación de publicaciones -->
                  <div class="pagination justify-content-center">
                      {{ $datos->links() }}
                  </div>
              @endisset
        </div>
    </div> <br>

</div>

@endsection

web/resources/views/clasificado/Hospedador/detalle.blade.php
<div class="card-body" >
    <h2 class="h2-responsive text-center"><strong>{{$alquilerhosp->titulo}}</strong></h2> <br>
        <div class="text-center">
          <img style="max-height: 500px; max-width: 500px;" class="img-thumbnail shadow" src="/imagenes/clasificados/hospedador/{{$alquilerhosp->imagen}}">
          <br><br>
          <h4 class="h4-responsive text-success"><strong>${{$alquilerhosp->precio}}/Mes</h5></strong></h4>
        
        </div>
    
        @if ($alquilerhosp->categoria === "Casa")
        <h5 class="h5-responsive"><i class="fas fa-home" style="font-size:20px;"></i> {{$alquilerhosp->categoria}}</h5>
     @elseif ($alquilerhosp->categoria === "Apartamento")
        <h5 class="h5-responsive"><i class="fas fa-building" style="font-size:20px;"></i></i> {{$alquilerhosp->categoria}}</h5>
     @else
        <h5 class="h5-responsive"><i class="fas fa-bed" style="font-size:20px;"></i> {{$alquilerhosp->categoria}}</h5>
     @endif
        <h6 class="h6-responsive heading"><i class="fas fa-map-marker-alt" style="font-size:20px;"></i> Ubicación:  {{$alquilerhosp->ubicacion}}</h6>
        <h6 class="h6-responsive"><i class="fas fa-info" style="font-size:20px;"></i> Descripción: {{$alquilerhosp->descripcion}}</h6>
        <hr>
    
    <!--Accordion wrapper-->
    <div class="accordion md-accordion shadow" id="accordionEx" role="tablist" >
      <!-- Accordion card -->

    <!-- Card header -->
    <div class="card-header bg-info shadow " role="tab" id="headingOne1">
        <a data-toggle="collapse" data-parent="#accordionEx" href="#collapscard1" aria-expanded="true"
          aria-controls="collapsecard">
          <h6 class="mb-0 text-white ">
            <i class=" fas fa-angle-down rotate-icon"></i> Detalles de {{$alquilerhosp->categoria}} 
          </h6>
        </a>
      </div>
   
      <!-- Card body -->
      <div id="collapscard1" class="collapse show thumb-shadow" role="tabpanel" aria-labelledby="headingOne1"
        data-parent="#accordionEx">
        <div class="col-xs-12 col-lg-12 text-justify">
            <div class="card-body" >
         
          <br>
          <label><i class="far fa-id-card"style="font-size:20px;"></i>  Estacionamiento: {{$alquilerhosp->estacionamiento}}</label>
          <br>
          <label><i class="fas fa-bed"style="font-size:20px;"></i>   habitaciones: {{$alquilerhosp->habitaciones}}</label>
          <br>
          <label><i class="fas fa-toilet"style="font-size:20px;"></i>  baños: {{$alquilerhosp->baños}}</label>
          <br>
          <label> <i class="fas fa-couch"style="font-size:20px;" ></i>  Amueblado: {{$alquilerhosp->amueblado}}</label>
    
        </div>
        </div>
      </div>
      <br>
        <!-- Card header -->
        <div class="card-header bg-info " role="tab" id="headingOne2">
          <a data-toggle="collapse" data-parent="#accordionEx" href="#collapscard2" aria-expanded="true"
            aria-controls="collapsecard">
            <h6 class="mb-0 text-white ">
              <i class=" fas fa-angle-down rotate-icon"></i> Información de Contacto 
            </h6>
          </a>
        </div>
     
        <!-- Card body -->
        <div id="collapscard2" class="collapse show thumb-shadow" role="tabpanel" aria-labelledby="headingOne1"
          data-parent="#accordionEx">
          <div class="col-xs-12 col-lg-12 text-justify">
              <div class="card-body" >
            <label><i class="far fa-id-badge"style="font-size:20px;"></i>  Nombre del Contacto: {{$alquilerhosp->nombre}}</label>
            <br>
            <label><i class="fas fa-mobile"style="font-size:20px;"></i>  Celular: {{$alquilerhosp->celular}}</label>
            <br>
            <label><i class="fas fa-at"style="font-size:20px;"></i>  Email: {{$alquilerhosp->email}}</label>                                  
          </div>
          </div>
        </div>

      </div>
      <!-- Accordion card -->
    
      <hr>
    
          <p class="h5 bold-text">Información de del contacto</p>
          <p><i class="fas fa-user" style="font-size:20px;"></i> Publicado por: <a href="{{route('perfil.verPerfil', $alquilerhosp->email)}}"> {{$alquilerhosp->email}}</a> </p>
          <p><i class="fas fa-ticket-alt"style="font-size:20px;"></i> Código de Publicación: {{$alquilerhosp->codigoPost}}</p> 
          <p><i class="fas fa-clock"style="font-size:20px;"></i> Publicado {{$alquilerhosp->created_at->diffForHumans()}}</p> 
        
    <div class="modal-footer">
        <button type="submit" class="btn btn-success" data-dismiss="modal">Cerrar</button>
    </div>
    </div>
    

web/resources/views/clasificado/Hospedador/formulario.blade.php
<form action="{{ route('alquilerhospedajes.store')}}" method="POST" enctype="multipart/form-data">
       @csrf
       <div class="form-group row">
            <label for="categoria" class="col-form-label col-sm-3">Categorías:</label>
                <div class="col-sm-8">
                 <select id="categoria" class="form-control" name="categoria" required>
                   <option disabled selected>---selecione una categoría---</option>
                    <option value="Apartamento">Apartamento</option>
                    <option value="Cuarto" >Cuarto</option>
                    <option value="Casa">Casa</option>
                </select>
                </div>
        </div>

        <div class="form-group row">
            <label for="titulo" class="col-form-label col-sm-3">Título:</label>
            <div class="col-sm-8">
            <input type="text"  name="titulo" id="titulo" class="form-control" placeholder="Título" tabindex="1">
            </div>
        </div>


        <div class="form-group row">
            <label for="ubicacion" class="col-form-label col-sm-3">Ubicación:</label>
            <div class="col-sm-8">
            <input type="text" name="ubicacion" id="ubicacion" class="form-control" placeholder="Ubicación" tabindex="1">
            </div>
        </div>


        <!-- Input de descripcion -->
        <div class="form-group row">
                <label for="descripcion" class="col-form-label col-sm-3">Descripción:</label>
                <div class="col-sm-8">
                <textarea class="form-control"  id="descripcion" name="descripcion" placeholder="Descripción"></textarea>
                </div>
              </div>


        <div class="form-group row">
            <label for="precio" class="col-form-label col-sm-3">Precio por Mes:</label>
            <div class="col-sm-8">
            <input class="form-control" id="precio" type="number" name="precio"  min="0" max="9999" step="0.01"  placeholder="B/." oninput="validity.valid||(value='');" required>
            </div>
        </div>


        <hr>
        <p class="h5">Detalles:</p>

        <!-- Input de Estacionamiento -->
              <div class="form-group row">
                <label for="estacionamiento" class="col-form-label col-sm-3">Estacionamiento:</label>
                <div class="col-sm-8">
                <select id="estacionamiento" class="form-control" name="estacionamiento" required>
                    <option value="No">No</option>
                    <option value="Sí">Sí</option>
               </select>
                </div>
              </div>

              <!-- Input de habitaciones -->
              <div class="form-group row">
                <label for="habitaciones" class="col-form-label col-sm-3">Habitaciones:</label>
                <div class="col-sm-8">
                <input class="form-control" id="habitaciones" name="habitaciones" type="number" min="1" max="99" step="1" oninput="validity.valid||(value='');" required>
                </div>
              </div>

               <!-- Input de Baños -->
               <div class="form-group row">
                <label for="habitaciones" class="col-form-label col-sm-3">Baños:</label>
                <div class="col-sm-8">
                <input class="form-control" id="baños" name="baños" type="number" min="1" max="99" step="1" oninput="validity.valid||(value='');" required>
                </div>
              </div>

              <!-- Input de Amueblada -->
              <div class="form-group row">
                <label for="amueblado" class="col-form-label col-sm-3">Amueblada:</label>
                <div class="col-sm-8">
                <select id="amueblado" class="form-control" name="amueblado" required>
                    <option value="No">No</option>
                    <option value="Sí">Sí</option>
                </select>
                </div>
              </div>
              <hr>


        <!-- Input de Imagen -->
         <div class="form-group row">
            <label for="imagen" class="col-form-label col-sm-3">Agregar Fotos:</label>
            <div class="col-sm-8">
            <input type="file" name="imagen" id="imagen" class="form-control" placeholder="Agregar foto" tabindex="1">
            </div>
        </div>


        <!-- Informacion de Contacto -->
        <hr>
        <p class="h5">Información de Contacto:</p>



        <!-- Input de Celular -->
        <div class="form-group row">
          <label for="Celular" class="col-form-label col-sm-3">Celular:</label>
          <div class="col-sm-8">
            <input type="text" name="celular" id="celular" class="form-control" placeholder="Celular" tabindex="1">
          </div>
        </div>





        <!-- Modal Footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-success">Publicar</button>
        </div>

      </form>

web/resources/views/clasificado/Hospedador/formularioUpdate.blade.php
<h2 class="h2-responsive text-center"><strong>{{$alquilerhosp->titulo}} ({{$alquilerhosp->codigoPost}})</strong></h2>
<form action="{{route('alquilerhospedajes.update', $alquilerhosp->id)}}" method="POST" enctype="multipart/form-data">
     @csrf

     <!-- Imagen actual del tutorias -->
     <div class="text-center">
            <img style="max-height: 400px; max-width: 400px;" class="img-thumbnail shadow" src="/imagenes/clasificados/hospedador/{{$alquilerhosp->imagen}}">
        </div> <br>

        <!-- Nueva Imagen -->
        <div class="form-group row p-2">
         <label for="imagen" class="col-form-label col-sm-3 font-weight-bold">Nueva Imagen</label>
         <input type="file" class="form-control-file col-sm-8" id="imagen" name="imagen" accept="image/*">
       </div>

       <div class="form-group row">
        <label for="categoria" class="col-form-label col-sm-3">Categorías:</label>
        <div class="col-sm-8">
            <select id="alqhos_categoria_{{$alquilerhosp->id}}" class="form-control" name="categoria" required>
                    <option value="Apartamento">Apartamento</option>
                    <option value="Cuarto" >Cuarto</option>
                    <option value="Casa">Casa</option>
                </select>
            </div>
        </div>

       <div class="form-group row">
            <label for="titulo" class="col-form-label col-sm-3">Título:</label>
            <div class="col-sm-8">
            <input type="text"  name="titulo" id="titulo" class="form-control" placeholder="Título" tabindex="1" value="{{$alquilerhosp->titulo}}">
            </div>
        </div>


        <div class="form-group row">
            <label for="ubicacion" class="col-form-label col-sm-3">Ubicación:</label>
            <div class="col-sm-8">
            <input type="text" name="ubicacion" id="ubicacion" class="form-control" placeholder="Ubicación" tabindex="1" value="{{$alquilerhosp->ubicacion}}">
            </div>
        </div>


        <!-- Input de descripcion -->
        <div class="form-group row">
                <label for="descripcion" class="col-form-label col-sm-3">Descripción:</label>
                <div class="col-sm-8">
                <textarea class="form-control"  id="descripcion" name="descripcion" placeholder="Descripción">{{$alquilerhosp->descripcion}}</textarea>
                </div>
              </div>


        <div class="form-group row">
            <label for="precio" class="col-form-label col-sm-3">Precio por Mes:</label>
            <div class="col-sm-8">
            <input class="form-control" id="precio" type="number" name="precio"  min="0" max="9999" step="0.01"  placeholder="B/." oninput="validity.valid||(value='');" value="{{$alquilerhosp->precio}}" required>
            </div>
        </div>


        <hr>
        <p class="h5">Detalles:</p>

        <!-- Input de Estacionamiento -->
              <div class="form-group row">
                <label for="estacionamiento" class="col-form-label col-sm-3">Estacionamiento:</label>
                <div class="col-sm-8">
                <select id="alqhos_estacionamiento_{{$alquilerhosp->id}}" class="form-control" name="estacionamiento" required>
                    <option value="No">No</option>
                    <option value="Sí">Sí</option>
               </select>
                </div>
              </div>

              <!-- Input de habitaciones -->
              <div class="form-group row">
                <label for="habitaciones" class="col-form-label col-sm-3">Habitaciones:</label>
                <div class="col-sm-8">
                <input class="form-control" id="habitaciones" name="habitaciones" type="number" min="1" max="99" step="1" oninput="validity.valid||(value='');" value="{{$alquilerhosp->habitaciones}}" required>
                </div>
              </div>

               <!-- Input de Baños -->
               <div class="form-group row">
                <label for="habitaciones" class="col-form-label col-sm-3">Baños:</label>
                <div class="col-sm-8">
                <input class="form-control" id="baños" name="baños" type="number" min="1" max="99" step="1" oninput="validity.valid||(value='');" value="{{$alquilerhosp->baños}}" required>
                </div>
              </div>

              <!-- Input de Amueblada -->
              <div class="form-group row">
                <label for="amueblado" class="col-form-label col-sm-3">Amueblada:</label>
                <div class="col-sm-8">
                <select id="alqhos_amueblado_{{$alquilerhosp->id}}" class="form-control" name="amueblado" required>
                    <option value="No">No</option>
                    <option value="Sí">Sí</option>
                </select>
                </div>
              </div>
              <hr>

               <!-- Informacion de Contacto -->
        <hr>
        <p class="h5">Información de Contacto:</p>



        <!-- Input de Celular -->
        <div class="form-group row">
          <label for="Celular" class="col-form-label col-sm-3">Celular:</label>
          <div class="col-sm-8">
            <input type="text" name="celular" id="celular" class="form-control" placeholder="Celular" tabindex="1" value="{{$alquilerhosp->celular}}">
          </div>
        </div>


        <!-- Modal Footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-success">Actualizar</button>
        </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#alqhos_categoria_{{$alquilerhosp->id}}').val('{{$alquilerhosp->categoria}}').change();
            $('#alqhos_estacionamiento_{{$alquilerhosp->id}}').val('{{$alquilerhosp->estacionamiento}}').change();
            $('#alqhos_amueblado_{{$alquilerhosp->id}}').val('{{$alquilerhosp->amueblado}}').change();

        });
    </script>

</form>