web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Activación del controlador de verificación de correo
Auth::routes(['verify' => true]);

//Ruta de Página principal
Route::resource('/', 'HomeController')->middleware(['checkUserStatus']);

//Ruta de perfil de usuario
Route::resource('miPerfil', 'PerfilController');
//Rutas para el crud de anuncios
Route::get('Perfil/Compraventa/show/{id}', 'AnunciosController@show')->name('Perfil.show');
Route::get('Perfil/Compraventa/detalles/{id}', 'AnunciosController@edit')->name('Perfil.detalles')->middleware(['auth']);
Route::post ('Perfil/update/{id}', 'AnunciosController@update')->name('Perfil.update')->middleware(['auth']);
Route::get('dts/{id}', 'AnunciosController@destroy')->name('dts');
//Rutas para el crud de tutorias
Route::get('Perfil/show2/{id}', 'TutoriasController@show')->name('Perfil.show2');
Route::get('Perfil/detalles2/{id}', 'TutoriasController@edit')->name('Perfil.detalles2')->middleware(['auth']);
Route::put ('Perfil/update2/{id}', 'TutoriasController@update')->name('Perfil.update2')->middleware(['auth']);
Route::get('dt/{id}', 'TutoriasController@destroy')->name('dt');
//Rutas para el crud de Bolsa de trabajo
Route::get('dB/{id}', 'BolsatrabajoController@destroy')->name('dtB');
//Rutas para el crud de Eventos
Route::get('Perfil/showE/{id}', 'EventoController@show')->name('Perfil.showE');
Route::get('Perfil/detallesE/{id}', 'EventoController@edit')->name('Perfil.detallesE')->middleware(['auth']);
Route::get('dE/{id}', 'EventoController@destroy')->name('dtE');
//Rutas para el crud de Alquiler y Hospedaje
Route::get('Perfil/showH/{id}', 'HospedajeController@show')->name('Perfil.showH');
Route::get('Perfil/detallesH/{id}', 'HospedajeController@edit')->name('Perfil.detallesH')->middleware(['auth']);
Route::put ('Perfil/updateH/{id}', 'HospedajeController@update')->name('Perfil.updateH')->middleware(['auth']);
Route::get('dtH/{id}', 'HospedajeController@destroy')->name('dtH');


//ruta para cargar carreras al formulario de editar el perfil
Route::get('miPerfil/getcarreras/{id}','PerfilController@getCarreras');
//Ruta de Actualización de Perfil
Route::post('miPerfil/updateProfile', 'PerfilController@updateProfile')->name('perfil.update')->middleware(['auth']);
//Ruta para mostrar los perfiles de los usuarios
Route::get('usuario/{email}', 'PerfilController@verPerfil')->name('perfil.verPerfil')->middleware(['auth','checkUserStatus']);
//Ruta de registro
Route::get('/register','RegistroController@getFacultades')->name('register');
Route::get('register/getcarreras/{id}','RegistroController@getCarreras');



//Rutas de Clasificados
Route::group(['prefix' => 'clasificado'], function () {
//Rutas de Compras/Ventas
Route::resource('anuncios','AnunciosController');
Route::get('/anuncios','AnunciosController@search')->name('anuncios.search');
Route::post('anuncios/update/{id}', 'AnunciosController@update')->name('anuncios.update')->middleware(['auth']);

//Ruta de tutorias
Route::resource('tutorias', 'TutoriasController');
Route::get('/tutorias','TutoriasController@search')->name('tutorias.search');
Route::post('tutorias/update/{id}', 'TutoriasController@update')->name('tutorias.update')->middleware(['auth']);

//Ruta de alquilerhospedaje
Route::resource('alquilerhospedajes', 'HospedajeController');
Route::get('/alquilerhospedajes','HospedajeController@search')->name('alquilerhospedajes.search');
Route::post('alquilerhospedajes/update/{id}', 'HospedajeController@update')->name('alquilerhospedajes.update')->middleware(['auth']);

});
//Ruta de bolsatrabajo
Route::resource('bolsatrabajos', 'BolsatrabajoController');
Route::get('bolsatrabajos','BolsatrabajoController@search')->name('bolsaDeTrabajo.search');
Route::post('bolsatrabajos/update/{id}', 'BolsatrabajoController@update')->name('bolsaDetrabajo.update')->middleware(['auth']);

//Ruta de Eventos
Route::resource('eventos','EventoController');
Route::get('/eventos','EventoController@searchE');
Route::post('eventos/update/{id}', 'EventoController@update')->name('eventos.update')->middleware(['auth']);

//Route::resource('eventos','EventoController@carga')->name('eventos');


## Rutas del panel de administración ##
    //Rutas de Gestión de Usuarios
    Route::get('usersAdmin/getUser/', 'AdminPanel\UsersAdminController@getUser')->name('usersAdmin.getUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/changeRole/{email}', 'AdminPanel\UsersAdminController@changeRole')->name('usersAdmin.changeRole')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/banUser/{email}', 'AdminPanel\UsersAdminController@banUser')->name('usersAdmin.banUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('usersAdmin/reactivateUser/{email}', 'AdminPanel\UsersAdminController@reactivateUser')->name('usersAdmin.reactivateUser')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::resource('usersAdmin', 'AdminPanel\UsersAdminController')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Gestión de Facultades y Carreras
    Route::resource('degreesAdmin', 'AdminPanel\DegreesAdminController')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newFacultad', 'AdminPanel\DegreesAdminController@newFacultad')->name('degreeAdmin.newFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editFacultad/{id}', 'AdminPanel\DegreesAdminController@editFacultad')->name('degreeAdmin.editFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteFacultad/{id}', 'AdminPanel\DegreesAdminController@deleteFacultad')->name('degreeAdmin.deleteFacultad')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/newCarrera/{id}', 'AdminPanel\DegreesAdminController@newCarrera')->name('degreeAdmin.newCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/editCarrera/{id}', 'AdminPanel\DegreesAdminController@editCarrera')->name('degreeAdmin.editCarrera')->middleware(['auth','auth.admin','checkUserStatus']);
    Route::post('degreeAdmin/deleteCarrera/{id}', 'AdminPanel\DegreesAdminController@deleteCarrera')->name('degreeAdmin.deleteCarrera')->middleware(['auth','auth.admin','checkUserStatus']);

    //Rutas de Moderación de Publicaciones
    Route::resource('postsMod', 'AdminPanel\PostsModController')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/aprobarTutPost/{id}', 'AdminPanel\PostsModController@aprobarTutPost')->name('postsMod.aprobarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarTutPost/{id}', 'AdminPanel\PostsModController@rechazarTutPost')->name('postsMod.rechazarTutPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarHosPost/{id}', 'AdminPanel\PostsModController@aprobarHosPost')->name('postsMod.aprobarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarHosPost/{id}', 'AdminPanel\PostsModController@rechazarHosPost')->name('postsMod.rechazarHosPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::post('postsMod/aprobarCyVPost/{id}', 'AdminPanel\PostsModController@aprobarCyVPost')->name('postsMod.aprobarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);
    Route::post('postsMod/rechazarCyVPost/{id}', 'AdminPanel\PostsModController@rechazarCyVPost')->name('postsMod.rechazarCyVPost')->middleware(['auth','auth.mod','checkUserStatus']);

    Route::get('/banned', function () {
      return view('auth.banned');
    });

web/app/Evento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Evento extends Model
{
  //referncia a la tabla que se va a utilizar
  protected $table = "eventos";

  public function anunciante(){
      return $this->hasOne('App\User','email','email');
 }
}

web/app/Http/Controllers/EventoController.php
<?php

namespace App\Http\Controllers;

use App\Evento;
use Illuminate\Http\Request;
use Carbon\Carbon;
use DB;

class EventoController extends Controller
{
    public function __construct()
    {
          Carbon::setLocale('es');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      //muestra los datos
      $datos = Evento::orderBy('created_at','desc')->paginate(10);

      return view('Eventos.eventos')->with(compact('datos'));
    }
    public function searchE(Request $request)
    {
       $search = $request->get('search');
       $datos = Evento::whereRaw('concat(codigoPost,titulo,lugar,costo,descripcion,facultad_nomb) like \'%' .$search .'%\' ')
                        ->orderBy('created_at','desc')
                        ->paginate(10);
       return view('Eventos.eventos',compact('datos'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,[
      'titulo' => 'required',
      'fecha' => 'required',
      'lugar' => 'required',
      'costo' => 'required',
      'facultad_nomb' => 'required',
      'descripcion' => 'required',
      ]);


      $eventos = new Evento();
      //Generación de Código de Publicación.
      $eventos->codigoPost = 'EV-' . (Evento::all()->max('id') + 1);
      $eventos->titulo= $request->input('titulo');
      $eventos->fecha= $request->input('fecha');
      $eventos->hora= $request->input('hora');
      $eventos->lugar= $request->input('lugar');
      $eventos->costo= $request->input('costo');
      $eventos->facultad_nomb= $request->input('facultad_nomb');
      $eventos->descripcion= $request->input('descripcion');
      $eventos->email = \Auth::user()->email;

      if ($request->hasFile('imagen')) {
        $file = $request->file('imagen');
        $name_image = time().$file->getClientOriginalName();
        $file->move(public_path().'/imagenes/eventos',$name_image);
        $eventos->imagen =$name_image;
    }

     //salvar en la base de datos
      $eventos->save();
        return back()->with('success','Evento: '.$eventos->titulo.' Creado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $datos = Evento::find($id);
      return view('Perfil.Eventos.show', compact('datos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
                   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          echo $request;
          $this->validate($request,[
            'titulo' => 'required',
            'fecha' => 'required',
            'lugar' => 'required',
            'costo' => 'required',
            'facultad_nomb' => 'required',
            'descripcion' => 'required',
            ]);

         $eventos = Evento::find($id);
          $eventos->titulo= $request->input('titulo');
          $eventos->fecha= $request->input('fecha');
          $eventos->hora= $request->input('hora');
          $eventos->lugar= $request->input('lugar');
          $eventos->costo= $request->input('costo');
          $eventos->facultad_nomb= $request->input('facultad_nomb');
          $eventos->descripcion= $request->input('descripcion');

          if($request->hasFile('imagen')){
            if ($eventos->imagen === 'post-placeholder.jpg')
            {
            }else {
            unlink(public_path().'/imagenes/eventos/'.$eventos->imagen);
            }
            $file = $request->file('imagen');
            $name_image = time().$file->getClientOriginalName();
            $file->move(public_path().'/imagenes/eventos/',$name_image);
            $eventos->imagen = $name_image;

          }

          $eventos->save();
          return back()->with('success','Los datos del evento ' . $eventos->titulo . ' se han actualizado exitosamente.');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { $file = Evento::where('id', $id)->find($id);
      $usr = (auth()->user()->email);

      if ($usr ===$file->email)
      {
        if ($file->imagen === 'post-placeholder.jpg')
        {
        Evento::where('id', $id)->delete();
        return back()->with('success','Evento eliminado exitosamente.');
        }
       else {
         $file = Evento::where('id', $id)->find($id);
         if(unlink(public_path().'/imagenes/eventos/'.$file->imagen)){
          $file->delete();
          return back()->with('success','Evento eliminado exitosamente.');
             }
       }
      }
     }
}

web/resources/views/Eventos/detalle.blade.php
<div class="card-body" >
    <h2 class="h2-responsive text-center"><strong>{{$evento->titulo}}</strong></h2> <br>
        <div class="text-center">
          <img style="max-height: 500px; max-width: 500px;" class="img-thumbnail shadow" src="/imagenes/eventos/{{$evento->imagen}}">
          <br><br>
          @if ($evento->costo == 0 )
          <h4 class="h4-responsive text-success"><strong>Gratuito</strong></h4>
            @else
            <h4 class="h4-responsive text-success"><strong>Admisión: ${{$evento->costo}}</strong></h4>
            @endif

        </div>


        <h6 class="h6-responsive"><i class="fas fa-calendar-alt" style="font-size:20px;"></i>  Fecha: {{$evento->fecha}}</h6>
        <h6 class="h6-responsive"><i class="fas fa-map-marker-alt" style="font-size:20px;"></i>  Ubicación: {{$evento->lugar}}</h6>
        <h6 class="h6-responsive"><i class="fab fa-product-hunt" style="font-size:20px;"></i>  Facultad:  {{$evento->facultad_nomb}}</h6>
        <h6 class="h6-responsive"><i class="fas fa-info" style="font-size:20px;"></i>  Descripción: {{$evento->descripcion}}</h6>

      <hr>

          <p class="h5 bold-text">Información de la Publicación</p>
          <p><i class="fas fa-user" style="font-size:20px;"></i> Publicado por: <a href="{{route('perfil.verPerfil', $evento->email)}}"> {{$evento->email}}</a> </p>
          <p><i class="fas fa-ticket-alt" style="font-size:20px;"></i> Código de Publicación: {{$evento->codigoPost}}</p>
          <p><i class="fas fa-clock" style="font-size:20px;"></i> Publicado {{$evento->created_at->diffForHumans()}}</p>


    <div class="modal-footer">
        <button type="submit" class="btn btn-success" data-dismiss="modal">Cerrar</button>
    </div>
    </div>

web/resources/views/Eventos/evento.blade.php
<div class="container">
    <div class="row">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded card ">
                <div class="card-body d-flex ">
                    <div class="col-md-8 px-3 ">
                        <h3 class="card-title ">{{$evento->titulo}}</h3>
                        <p class="card-text"><i class="fas fa-map-marker-alt"></i> {{$evento->lugar}}</p>
                            <p class="card-text"><i class="fas fa-calendar-alt"></i> {{strftime("%d-%m-%Y",strtotime($evento->fecha))}} a las {{date("g:ia", strtotime($evento->hora))}} </p>
                            <p class="card-text"><i class="fas fa-hourglass"></i> {{\Carbon\Carbon::parse($evento->fecha)->diffForHumans()}}</p>
                            <p class="card-text"><i class="fas fa-clock"></i> Publicado {{$evento->created_at->diffForHumans()}}</p>                   
                            @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Ver más Detalles','id_modal'=>'anun'.$id,'title'=>'Detalle del evento','vista'=>'Eventos.detalle'])
                    </div>
                    <div class="text-right view view-cascade overlay"  width="500px">
                        <img class="card-img-top shadow" src="/imagenes/eventos/{{$evento->imagen}}"
                        class="pull-left img-responsive img-thumbnail rounded">
                         <!-- Si el costo del evento es de 0$, mostramos el mensaje 'Gratuito' -->
                         @if ($evento->costo == 0)
                            <h5 class="card-center text-success font-weight-bold text-right"> Gratuito </h5>
                          @else
                            <h5 class="card-center text-success font-weight-bold text-right">Admisión: ${{$evento->costo}}</h5>
                          @endif
                    </div>
                </div>
            </div>
    </div>
</div>

web/resources/views/Eventos/eventos.blade.php
@extends('layouts.app')
@section('content')
 <!-- Back to top -->        
 @include('Homes.BacktoTop')

<!--Jumbotron -->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Sección de Eventos</h1>
    <p class="lead">Aquí podrás encontrar información sobre las próximas conferencias, ferias y eventos que se realizan en la universidad.</p>
  </div>
</div>

<div class="container">  
    @if(count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif     

   <!-- Formulario de Búsqueda -->
    <form action="/eventos" method="get">
      <div class="form-group row justify-content-center">         
        <div class="col-auto">
          <input class="form-control form-control" type="search" placeholder="Buscar Evento" aria-label="Search" name="search" >
        </div>    

        <div class="col-auto">
            <button class="btn btn-success col" type="submit"> <i class="fas fa-search"></i> </button> 
        </div> 
      </div>                      
    </form>  
    @if(auth()->check() && ( auth()->user()->hasAnyRole('Administrador') || auth()->user()->hasAnyRole('Moderador') ) )
    <div class="text-center"> 
      @include('clasificado.Anuncios.modal', $data=['btn_nombre'=>'Agregar Evento','id_modal'=>'mod1','title'=>'AGREGA EVENTOS AQUÍ','vista'=>'Eventos.formulario'])
    </div> 
    @endif
    
  
  <br>
        <div id="eventos" class="row justify-content-center">
            <div class="col-md-8">
                <!-- Paginación de publicaciones -->
                <div class="pagination justify-content-center">
                      {{ $datos->links() }}       
                </div>
                <!-- Verificamos si la variable existe -->
                @isset($datos)
                  @if($datos->count() > 0)
                    @foreach ($datos as $evento)
                            @include('Eventos.evento', $evento)
                    @endforeach
                  @else
                    <div class="alert alert-info text-center" role="alert">
                      No existen anuncios de eventos publicados en estos momentos.
                    </div>
                  @endif                     
                    <!-- Paginación de publicaciones -->
                    <div class="pagination justify-content-center">
                      {{ $datos->links() }}       
                    </div>
                 @endisset                    
          </div>


        </div>

</div>

@endsection

web/resources/views/Eventos/formulario.blade.php
<form action="{{ route('eventos.store')}}" method="POST" enctype="multipart/form-data">
 @csrf

 <!-- Input del Título del Evento-->
        <div class="form-group row">
          <label for="titulo" class="col-form-label col-sm-3">Título del Evento:</label>
          <div class="col-sm-8">
            <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Título" required>
          </div>
        </div>

        <!-- Input de Fecha -->
              <div class="form-group row">
                <label for="fecha" class="col-form-label col-sm-3">Fecha:</label>
                <div class="col-sm-8">
                  <input type="date" name="fecha" id="fecha" class="form-control" placeholder="00/00/0000" required >
                </div>
              </div>

        <!-- Input de Hora -->
        <div class="form-group row">
                <label for="fecha" class="col-form-label col-sm-3">Hora:</label>
                <div class="col-sm-8">
                  <input type="time" name="hora" id="hora" class="form-control" placeholder="00:00" required >
                </div>
              </div>

        <!-- Input de Lugar -->
            <div class="form-group row">
              <label for="lugar" class="col-form-label col-sm-3">Lugar:</label>
              <div class="col-sm-8">
                <input type="text" name="lugar" id="lugar" class="form-control" placeholder="Lugar" required>
              </div>
            </div>

            <!-- Input de Costo-->
            
                <div class="form-group row">
                  <label for="costo" class="col-form-label col-sm-3">Costo de Admisión:</label>
                  <div class="col-sm-8">
                    <input type="number" name="costo"  min="0" max="9999" step="0.01" name="costo" id="costo" class="form-control" placeholder="B/." required>
                  </div>
                </div>
                <!-- Input de Facultades-->
                <div class="form-group row">
                     <label for="facultad_nomb" class="col-form-label col-sm-3">Facultades:</label>
                         <div class="col-sm-8">
                          <select id="facultad_nomb" class="form-control" name="facultad_nomb" required>
                            <option value="Facultad de Ciencias y Tecnología">Facultad de Ciencias y Tecnología</option>
                            <option value="Facultad de Ingeniería Civil" >Facultad de Ingeniería Civil</option>
                            <option value="Facultad de Ingeniería Eléctrica">Facultad de Ingeniería Eléctrica</option>
                            <option value="Facultad de Ingeniería Industrial">Facultad de Ingeniería Industrial</option>
                            <option value="Facultad de Ingeniería Mecánica">Facultad de Ingeniería Mecánica</option>
                            <option value="Facultad de Ingeniería de Sistemas Computacionales">Facultad de Ingeniería de Sistemas Computacionales</option>
                         </select>
                         </div>
                 </div>
                    <!-- Input de Descripcion -->
                     <div class="form-group row">
                         <label for="descripcion" class="col-form-label col-sm-3">Descripción:</label>
                         <div class="col-sm-8">
                         <textarea class="form-control" id="message-text" name="descripcion" placeholder="Descripcion"></textarea required>
                           </div>
                     </div>

                      <!-- Input de Imagen-->
                      <div class="form-group row">
                         <label for="addfoto" class="col-form-label col-sm-3">Agregar Poster:</label>
                         <div class="col-sm-8">
                         <input type="file" name="imagen" id="imagen" class="form-control" placeholder="Add Foto" tabindex="1">
                         </div>
                     </div>

                      <!-- Modal Footer -->
                      <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-success">Publicar</button>
                      </div>
                    </form>

web/resources/views/Eventos/formularioUpdate.blade.php
<h2 class="h2-responsive text-center"><strong>{{$evento->titulo}} ({{$evento->codigoPost}})</strong></h2>
<form action="{{route('eventos.update', $evento->id)}}" method="POST" enctype="multipart/form-data">
     @csrf
        <!-- Imagen actual del evento -->
        <div class="text-center">
            <img style="max-height: 400px; max-width: 400px;" class="img-thumbnail shadow" src="/imagenes/eventos/{{$evento->imagen}}">
        </div> <br>   

        <!-- Nueva Imagen -->
        <div class="form-group row p-2">
         <label for="imagen" class="col-form-label col-sm-3 font-weight-bold">Nueva Imagen</label>
         <input type="file" class="form-control-file col-sm-8" id="imagen" name="imagen" accept="image/*">
       </div>
                   
        <!-- Título del Evento -->
        <div class="form-group row p-2">
            <label for="titulo" class="col-form-label col-sm-3 font-weight-bold">Título del Evento:</label>
            <input type="text" name="titulo" id="titulo" class="form-control col-sm-8" value="{{$evento->titulo}}" required>
        </div>

        <!-- Fecha del Evento -->
        <div class="form-group row p-2">
            <label for="fecha" class="col-form-label col-sm-3 font-weight-bold">Fecha:</label>
            <input type="date" name="fecha" id="fecha" class="form-control col-sm-8" value="{{$evento->fecha}}" required>
        </div> 

        <!-- Hora del Evento -->
        <div class="form-group row p-2">
            <label for="hora" class="col-form-label col-sm-3 font-weight-bold">Hora:</label>
            <input type="time" name="hora" id="hora" class="form-control col-sm-8" value="{{$evento->hora}}" required>
        </div>  

        <!-- Lugar del Evento -->
        <div class="form-group row p-2">
            <label for="lugar" class="col-form-label col-sm-3 font-weight-bold">Lugar:</label>
            <input type="text" name="lugar" id="lugar" class="form-control col-sm-8" value="{{$evento->lugar}}" required>
        </div>

        <!-- Costo del Evento -->
        <div class="form-group row p-2">
            <label for="costo" class="col-form-label col-sm-3 font-weight-bold">Costo:</label>
            <input type="number" name="costo"  min="0" max="9999" step="0.01" class="form-control col-sm-8" value="{{$evento->costo}}">
        </div>

  

        <!-- Facultad del Evento -->
        <div class="form-group row p-2">
            <label for="costo" class="col-form-label col-sm-3 font-weight-bold">Facultad:</label>
            <select id="evento_facultad_nomb_{{$evento->id}}" name="facultad_nomb" class="form-control col-sm-8" required>
                <option value="Facultad de Ciencias y Tecnología">Facultad de Ciencias y Tecnología</option>
                <option value="Facultad de Ingeniería Civil">Facultad de Ingeniería Civil</option>
                <option value="Facultad de Ingeniería Eléctrica">Facultad de Ingeniería Eléctrica</option>
                <option value="Facultad de Ingeniería Industrial">Facultad de Ingeniería Industrial</option>
                <option value="Facultad de Ingeniería Mecánica">Facultad de Ingeniería Mecánica</option>
                <option value="Facultad de Ingeniería de Sistemas Computacionales">Facultad de Ingeniería de Sistemas Computacionales</option>
            </select>
        </div>

        <!-- Descripción del Evento -->
        <div class="form-group row p-2">
            <label for="descripcion" class="col-form-label col-sm-3 font-weight-bold">Descripción:</label>
            <textarea class="form-control col-sm-8" name="descripcion" rows="4" cols="80">{{$evento->descripcion}}</textarea>
        </div>

        <!-- Modal Footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-success">Actualizar</button>
        </div> 
        <script type="text/javascript">
            $(document).ready(function () {
            $('#evento_facultad_nomb_{{$evento->id}}').val('{{$evento->facultad_nomb}}').change();
        })
</script>       
</form>   